### ISSUE TITLE
(DST) changes do not necessarily occur on the same date every year.

### ISSUE THREAD

**Issue by ali32b** [JChristensen/Timezone#10]
Daylight Saving Time (DST) changes do not necessarily occur on the same date every year.

**Comment by JChristensen** [comment]
Yes, I am very much aware of this and the library is so coded. If there is an actual issue, please submit a [SSCCE](http://www.sscce.org/).

**Comment by ali32b** [comment]
Let me give you and example.This library works for countries that their DST happens exactly on same weekday(ie monday) every year.For countries like Iran(Tehran) DST starts on "monday" 2016 while on 2017 starts on "wednesday".So we can not create TimeChangeRule  to work every year.I hope I've explained that well.
[https://www.timeanddate.com/time/zone/iran/tehran](url)

**Comment by JChristensen** [comment]
Thanks for the clarification, I was not familiar with IRDT nor did I understand what country you were referring to.
Since the change dates for IRDT do not follow a rule, the only advice I could offer would be to code a rule for each year and then reference the proper rule based on the current year. Alternately, use a single rule and code a table of change dates which is used to modify the rule on the fly.
