### ISSUE TITLE
library.properties too strict

### ISSUE THREAD

**Issue by jackjansen** [JChristensen/Timezone#54]
The timezone library has a `library.properties` that lists `architectures=avr`. This is too strict: the library works just fine on other architectures, I've been using it on both esp8266 and esp32 successfully for a long time.

But now I am working on a platformio project where I need to set `lib_compat_mode = strict` (because I have one dependent library that only builds on esp32). And now Timezone isn't included anymore because of the `architectures=avr`.

**Comment by JChristensen** [comment]
I am aware that many people use the Timezone library on other architectures but I only work with the AVR architecture. Since I am unable to test or debug on other architectures, I prefer not to advertise the library as such.
If PlatformIO doesn't show the library when working with other architectures, then it's being too restrictive IMHO. The Arduino IDE suffers from the same problem.
Regardless, if you will change [the architectures line](https://github.com/JChristensen/Timezone/blob/7cf1425b4ee598573e85b6fa124d4514f71c2586/library.properties#L9) to read as follows, then your issue should be solved:
```c++
architectures=*
```
