### ISSUE TITLE
tcr->offset fails without calling toLocal prior to it

### ISSUE THREAD

**Issue by sezanzeb** [JChristensen/Timezone#63]
Can you please add a `getOffset(time_t time, TimeChangeRule *tcr)` function, or maybe just `getOffset(TimeChangeRule *tcr)` which uses `now()` as the time, that does the necessary steps to actually get the offset? This is a hidden dependency

```cpp
    time_t utc = now();
    time_t local = myTZ.toLocal(utc, &tcr);
    Serial.print(tcr->offset);
```

works

```cpp
    // time_t utc = now();
    // time_t local = myTZ.toLocal(utc, &tcr);
    Serial.print(tcr->offset);
```

fails with a core dump / backtrace.

**Comment by JChristensen** [comment]
`tcr` is a pointer to a `TimeChangeRule`.

Calling `toLocal()` returns a pointer to the `TimeChangeRule` that was used to do the time conversion. The idea is to let the caller know _which_ rule was used for the conversion.

In the second code snippet above, it would appear that `tcr` was never given a value, since `toLocal()` had not been called to do a conversion.

Dereferencing an empty pointer is sure to cause trouble!

**Comment by sezanzeb** [comment]
> Dereferencing an empty pointer is sure to cause trouble!

I see. low-level programming is still a mystery to me

**Comment by JChristensen** [comment]
Pointers are powerful but can be dangerous.
Why not just use the first code snippet? I don't see a downside.

**Comment by sezanzeb** [comment]
yeah sure I'm using that one (https://github.com/sezanzeb/arduino-wxa50-alarm/blob/main/arduino-wxa50-alarm/time.cpp).

I just ran into the issue and it took some time until I figured out it was because I removed the call to `toLocal` previously. Thanks for pointing out that the pointer was empty.
